### ISSUE TITLE
Usablity of custom middleware

### ISSUE THREAD

**Issue by nullpixel** [RobinBuschmann/express-controllers#1]
are you able to use custom, route specific middleware with this?

**Comment by RobinBuschmann** [comment]
You mean, when using [this](https://github.com/RobinBuschmann/express-controllers#defining-routes-directly-in-controllers-with-typescript) functionality? For this there is currently no annotations available.

Did you try this repo: https://github.com/pleerock/routing-controllers ?

**Comment by nullpixel** [comment]
Nope, I haven’t seen that. I’ll try it, thanks!
